services:
  tr_db:
    image: postgres:13
    environment:
      POSTGRES_DB: transactional
      POSTGRES_USER: vada
      POSTGRES_PASSWORD: vada
    ports: ["5432:5432"]
    volumes:
      - tr_data:/var/lib/postgresql/data

  wh_db:
    image: postgres:13
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_USER:  vada
      POSTGRES_PASSWORD:  vada
    ports: ["5433:5432"]
    volumes:
      - wh_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: flask_app
    environment:
      TR_DATABASE_URI: postgresql://vada:vada@tr_db:5432/transactional
      WH_DATABASE_URI: postgresql://vada:vada@wh_db:5432/warehouse
    depends_on:
      - tr_db
      - wh_db
    ports:
      - "5000:5000"
      - "5001:5001"
    entrypoint: ["sh", "/app/entrypoint.sh"]

volumes:
  tr_data:
  wh_data:
